### ISSUE TITLE
URL to resources may be wrong

### ISSUE THREAD

**Issue by kitmacleod** [universeworkshops/intro-to-graphql#2]
Thanks @krider2010 for sharing GraphQL workshop materials. Your link to 'resources' is to this repo/page (circular), when maybe you meant https://github.com/krider2010/graphql-intro-resources. Others who were not able to attend the event, may find these MD files useful esp. queries.md.

**Comment by krider2010** [comment]
You are very right!

I have fixed this now. Apologies for the error and thank you so much for brining it to my attention ✨
